# Site settings
title: About me
email: fobia3d@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal page

#baseurl: "https://github.com/tyurind/tyurind.github.io" # the subpath of your site, e.g. /blog/
#url: "tyurind.github.io" # the base hostname & protocol for your site

# highlighter: pygments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyurind.ru" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TyurinD
github_username:  tyurind

repository: tyurind/tyurind.github.io

# Build settings
markdown: kramdown

# Расположение
source:      .
destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
# data_source: ./_data
# collections: null

# Обработка текста
safe:         false
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM

plugins:
  - jekyll-feed

theme: jekyll-theme-minimal
